more workflow jobs

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -16,7 +16,7 @@ on:
 # A workflow run is made up of one or more jobs that can run sequentially or in parallel
 jobs:
 
-  CheckPaclet:
+  CheckDefinitionNotebook:
     # The type of runner that the job will run on
     runs-on: ubuntu-latest
     container:
@@ -35,12 +35,60 @@ jobs:
         env:
           WOLFRAMSCRIPT_ENTITLEMENTID: ${{ secrets.WOLFRAM_LICENSE_ENTITLEMENT_ID }}
           CHECKGITHUBPACLET_PERMISSIONS_KEY: ${{ secrets.CHECKGITHUBPACLET_PERMISSIONS_KEY }}
-        run: |
-          wolframscript Scripts/CheckPaclet.wls
+        run: wolframscript Scripts/CheckDefinitionNotebook.wls
           
       - name: Upload build artifacts
+        if: success() || failure()    # run this step even if previous step failed
         uses: actions/upload-artifact@v2
         with:
           name: artifacts
           path: build/
           if-no-files-found: error
+
+  CodeInspection:
+    # The type of runner that the job will run on
+    runs-on: ubuntu-latest
+    container:
+      image: wolframresearch/wolframengine:latest
+      options: --user root
+    env:
+      WOLFRAM_SYSTEM_ID: Linux-x86-64
+
+    # Steps represent a sequence of tasks that will be executed as part of the job
+    steps:
+      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
+      - uses: actions/checkout@v2
+
+      # Runs a single command using the runners shell
+      - name: Run CodeInspector on Paclet files
+        env:
+          WOLFRAMSCRIPT_ENTITLEMENTID: ${{ secrets.WOLFRAM_LICENSE_ENTITLEMENT_ID }}
+        run: wolframscript Scripts/CodeInspection.wls
+
+  TestReport:
+    # The type of runner that the job will run on
+    runs-on: ubuntu-latest
+    container:
+      image: wolframresearch/wolframengine:latest
+      options: --user root
+    env:
+      WOLFRAM_SYSTEM_ID: Linux-x86-64
+
+    # Steps represent a sequence of tasks that will be executed as part of the job
+    steps:
+      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
+      - uses: actions/checkout@v2
+
+      # Runs a single command using the runners shell
+      - name: Run all tests
+        env:
+          WOLFRAMSCRIPT_ENTITLEMENTID: ${{ secrets.WOLFRAM_LICENSE_ENTITLEMENT_ID }}
+        run: wolframscript Scripts/TestReport.wls
+
+      - name: Test Report
+        uses: dorny/test-reporter@v1
+        if: success() || failure()    # run this step even if previous step failed
+        with:
+          name: JEST Tests            # Name of the check run which will be created
+          path: test-results/results.xml    # Path to test results
+          reporter: java-junit        # Format of test results
